version: '3.8'
services:
  web:
    build: .
    command:
      - /bin/bash
      - -c
      - |
        python manage.py collectstatic --noinput --skip-checks
        python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    volumes:
      - web-data:/code

volumes:
  web-data: