# Generated by Django 3.2.8 on 2021-11-12 08:33

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20211029_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companyproject',
            name='employees',
            field=models.ManyToManyField(related_name='all_employees', to=settings.AUTH_USER_MODEL, verbose_name='Участники'),
        ),
    ]
