# Generated by Django 3.2.8 on 2021-11-12 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0003_alter_companyproject_employees'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='department',
            constraint=models.CheckConstraint(check=models.Q(('name__contains', 'петя')), name='department_name'),
        ),
    ]
